name: hf-cookbook
channels:
  - conda-forge
  - defaults
dependencies:
  - Pillow
  - accelerate
  - aiohttp
  - boto3
  - bs4
  - datasets
  - diffusers
  - ftfy
  - huggingface_hub
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - openai
  - openpyxl
  - pandas
  - pydantic
  - pymongo
  - scikit-learn
  - scipy
  - sentencepiece
  - tqdm
  - transformers
  - umap-learn
  - pip
  - pip:
    - argilla
    - awscli
    - aws-jupyter-proxy
    - bitsandbytes
    - chromadb
    - distilabel
    - faiss-cpu
    - faiss-gpu
    - fiftyone
    - google-search-results
    - langchain
    - langchain-community
    - langchain-openai
    - langchainhub
    - llama-index
    - outlines
    - pacmap
    - peft
    - sentence-transformers
    - serpapi
    - setfit
    - wandb
    - xformers